### ISSUE TITLE
CSS completion from html tags

### ISSUE THREAD

**Issue by lyndhurst** [mattn/vim-lsp-settings#421] opened 2021-05-16 10:07 UTC
Hi,
I am trying to migrate from coc.nvim, and I was wondering if there was a way with vim-lsp to emulate the css attributes completion within html, vue or django template files offered by the [vscode-html-css extension](https://github.com/ecmel/vscode-html-css#features).
Thanks for your time.

**Comment by yaegassy** [comment] 2021-05-16 10:52
@lyndhurst vim-lsp is a plugin that works with "Language Server".

Unfortunately, there is no Langauge Server equivalent to the `vscode-html-css` extension as far as I know. :(

(By the way, I'm the author of [coc-html-css-support](https://github.com/yaegassy/coc-html-css-support))

**Comment by lyndhurst** [comment] 2021-05-16 14:20
Ok, thanks for answering so quickly.

I was actually trying vim-lsp after setting up a complete vimrc file around coc.nvim, just to try both alternatives. I do like some aspects of both so far, and feel they are great additions to vim.

You contributing to both coc.nvim, and vim-lsp makes me curious though, I now wonder if it is possible / manageable to use some features of both simultaneously, like vim-lsp for language servers, and coc.nvim for vscode extensions like yours, or coc-html-django that I also like.

Anyway thank you for both of your contributions then ! :1st_place_medal:

**Comment by yaegassy** [comment] 2021-05-17 01:37
@lyndhurst If the issue is resolved, please close this issue.

**Closed** 2021-05-17 16:10 UTC
